language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository 
script:
    - ./gradlew build
before_install:
    - chmod +x gradlew
branches:
  only:
    - master
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file_glob: true
  file: 'app/build/outputs/apk/*.apk'
  skip_cleanup: true
  on:
    tags: true
    
